### ISSUE TITLE
是不是，不会跑？

### ISSUE THREAD

**Issue by zgcwkj** [i11us0ry/goon#3]
2021/08/28 10:22:24 ::module    :ssh brute
2021/08/28 10:22:24 ::host      :1
2021/08/28 10:22:24 ::user      :1
2021/08/28 10:22:24 ::pass      :8908
2021/08/28 10:22:24 ::total     :8908
2021/08/28 10:22:24 ::timeout   :30
2021/08/28 10:22:24 ::thread    :50
2021/08/28 10:22:24 ::ofile     :./result/brute_1630117338.txt

---------------------------------------------------------------------------------------------

[Progress]::|  8908/8908

[Success]:: | 2021/08/28 10:22:28   0 assets were found in 4 seconds

都没用 5 秒，这么快？

**Comment by i11us0ry** [comment]
我设置了资产识别和存活检测机制，资产识别就是判断它是否属于ssh，存活检测就是判断进行ssh爆破时是否返回密码错误，如果不是则说明无法爆破，就是返回失败，当然如果您的资产确实为ssh，也确实还失败的话可以把资产私发我，如果可以的话，我看看咋回事



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月28日(周六) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 是不是，不会跑？ (#3)




 
2021/08/28 10:22:24 ::module    :ssh brute
 2021/08/28 10:22:24 ::host      :1
 2021/08/28 10:22:24 ::user      :1
 2021/08/28 10:22:24 ::pass      :8908
 2021/08/28 10:22:24 ::total     :8908
 2021/08/28 10:22:24 ::timeout   :30
 2021/08/28 10:22:24 ::thread    :50
 2021/08/28 10:22:24 ::ofile     :./result/brute_1630117338.txt
 
 
[Progress]::|  8908/8908
 
[Success]:: | 2021/08/28 10:22:28   0 assets were found in 4 seconds
 
都没用 5 秒，这么快？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zgcwkj** [comment]
任意 IP 都不行，Win 端，

**Comment by i11us0ry** [comment]
嗯嗯，感谢反馈，待会就更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 中午12:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [i11us0ry/goon] 是不是，不会跑？ (#3)




 
任意 IP 都不行，Win 端，
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by i11us0ry** [comment]
更新了，师傅可以再看看

**Comment by zgcwkj** [comment]
我这无法测试了，我把我的文件删除了，不好意思！
