### ISSUE TITLE
如何调用已扫描到的ip.txt

### ISSUE THREAD

**Issue by ttsite** [i11us0ry/goon#4]
怎么调用指定的ip.txt列表进行扫描。并指定user和pass 。可以这么用吗。如果可以格式是什么？

**Comment by i11us0ry** [comment]
可以的 -ifile是输入文件 包括ip列表，url列表。
指定user和pass用-user，-pass，指定user文件和pass文件用-ufile和-pfile
更多参数参考readme.md

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月11日(周六) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 如何调用已扫描到的ip.txt (Issue #4)




 
怎么调用指定的ip.txt列表进行扫描。并指定user和pass 。可以这么用吗。如果可以格式是什么？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
